average calculation
g4rb4g3/ABRPTransmitter pull request #4
Opened 2019-10-13 19:30 UTC by SamuelBrucksch

moved AsycHttpClient to top and set timeout smaller than update interval
added average calculation and tests
corrected typos

2019-10-13 19:31 UTC, SamuelBrucksch commented
@g4rb4g3 please review. 

Nicht mein schönster code aber es funktioniert. Average ist eine extra Klasse, damit ich die Funktionalität testen kann ohne was von den libs zu mocken. Sonst kommen Fehler und mit Mocks unter Android kenn ich mich noch nicht so aus.

2019-10-17 21:22 UTC, g4rb4g3 requested changes
vielen dank nochmal für deine unterstützung! hab eventuell eine lösung für das timer problem in der average klasse. schau es dir mal an und gib mir bescheid was du davon hältst.

2019-10-17 21:22 UTC, g4rb4g3 commented on app/src/main/java/g4rb4g3/at/abrptransmitter/Average.java
> +        return consumptionSum / updateInterval;
ich denke es wäre besser die verstrichene zeit anhand von intervalStart direkt zu messen und diese dann zum berechnen heranzuziehen.
dann sollte es auch kein problem damit geben wenn der timer zu spät auslöst. 
![grafik](https://user-images.githubusercontent.com/646435/67048490-9ad8be80-f134-11e9-86c5-6f791226385b.png)

2019-10-18 04:39 UTC, SamuelBrucksch commented
Das hatte ich auch versucht aber da kam auch nur Mist bei raus. Möglicherweise hatte ich aber auch einen Fehler in der Berechnung, probier ich nochmal aus.

2019-10-18 09:38 UTC, SamuelBrucksch commented
Hab das ganze mal angepasst, bitte noch nicht mergen, muss das nochmal testen....

2019-10-21 04:25 UTC, SamuelBrucksch commented
Bin gestern nochmal gefahren, könnte keine komischen Werte mehr feststellen. Scheint jetzt also richtig zu funktionieren.

2019-10-21 17:17 UTC, merged